version: "3.1"

services:
  frontend:
    build:
      context: .
    ports:
      - "127.0.0.1:3001:8080"
    networks:
      - evfront
    tmpfs:
      - /tmp
    read_only: true
    volumes:
      - /var/cache/nginx
      - /var/run
    security_opt:
      - no-new-privileges:true
    restart: on-failure

networks:
  evfront:
