version: "3.9"

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=evdata
      - POSTGRES_PASSWORD=evdata
    networks:
      - evdata
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  evdata:
