version: "3.9"

services:
  api:
    build:
      context: .
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql+psycopg2://evdata:evdata@postgres:5432/evdata
    ports:
      - "3000:3000"
    networks:
      - evdata
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=evdata
      - POSTGRES_PASSWORD=evdata
    networks:
      - evdata
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  evdata:
