name: Code Quality Workflow

on: [push]

jobs:

  pylint:
    name: Pylint code scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install pipenv
        pipenv install pylint
    - name: Analysing the code with pylint
      run: |
        pipenv run pylint --disable=import-error $(git ls-files '*.py')

  semgrep:
    name: Semgrep scan
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    # To skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch project source with GitHub Actions Checkout.
      - uses: actions/checkout@v3
      # Run the "semgrep ci" command on the command line of the docker image.
      - run: semgrep ci
        env:
           # Add the rules that Semgrep uses by setting the SEMGREP_RULES environment variable.
           SEMGREP_RULES: p/default

  kics:
    name: Kics IaC scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run kics scan
      uses: checkmarx/kics-github-action@v1.5
      with:
        path: 'backend/Dockerfile'
        output_path: results/
        fail_on: medium,high
        disable_full_descriptions: false
        token: ${{ secrets.GITHUB_TOKEN }}
        enable_comments: true
        ignore_on_exit: results
        verbose: true
    - name: display kics results
      run: |
        cat results/results.json
